"use client";

import { Flag, Link2, MessageSquareText, MessagesSquare, ShieldQuestion } from "lucide-react";
import { useRef, type PointerEvent as ReactPointerEvent } from "react";
import type { RootState } from "@/store";
import { useAppDispatch, useAppSelector } from "@/store/hooks";
import { dialogueEditorConnectionCancelled, dialogueEditorConnectionSelected, dialogueEditorConnectionStarted, dialogueEditorConnectionTargetSelected, dialogueEditorNodeDragEnded, dialogueEditorNodeDragStarted, dialogueEditorNodeMoved, dialogueEditorNodeSelected } from "../questSlice";
import type { DialogueNode } from "./types";

const width = 1180, height = 720, cardWidth = 220, cardHeight = 112;
const pathFor = (a: DialogueNode, b: DialogueNode) => { const x1 = a.position.x + cardWidth, y1 = a.position.y + cardHeight / 2, x2 = b.position.x, y2 = b.position.y + cardHeight / 2, bend = Math.max(70, Math.abs(x2 - x1) * .45); return `M ${x1} ${y1} C ${x1 + bend} ${y1}, ${x2 - bend} ${y2}, ${x2} ${y2}`; };

const DialogueGraph = () => {
  const dispatch = useAppDispatch();
  const editor = useAppSelector((state: RootState) => state.plugins.quest.editor.dialogueEditor);
  const ref = useRef<HTMLDivElement>(null);
  const point = (event: ReactPointerEvent) => { const bounds = ref.current?.getBoundingClientRect(); return bounds ? { x: event.clientX - bounds.left, y: event.clientY - bounds.top } : { x: 0, y: 0 }; };
  return <div ref={ref} className={`relative border border-slate-800 bg-slate-950/70 ${editor.pendingConnection ? "cursor-crosshair" : ""}`} style={{ width, height, backgroundImage: "linear-gradient(rgba(51,65,85,.18) 1px, transparent 1px), linear-gradient(90deg, rgba(51,65,85,.18) 1px, transparent 1px)", backgroundSize: "24px 24px" }} onClick={() => editor.pendingConnection ? dispatch(dialogueEditorConnectionCancelled()) : dispatch(dialogueEditorNodeSelected(null))} onPointerMove={(event) => { if (!editor.draggingNode) return; const p = point(event); dispatch(dialogueEditorNodeMoved({ nodeId: editor.draggingNode.nodeId, position: { x: Math.max(0, Math.min(width - cardWidth, p.x - editor.draggingNode.offset.x)), y: Math.max(0, Math.min(height - cardHeight, p.y - editor.draggingNode.offset.y)) } })); }} onPointerUp={() => dispatch(dialogueEditorNodeDragEnded())}>
    <svg className="absolute inset-0 h-full w-full"><defs><marker id="dialogue-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="#c084fc" /></marker></defs>{editor.document.connections.map((link) => { const source = editor.document.nodes.find((node) => node.id === link.sourceNodeId), target = editor.document.nodes.find((node) => node.id === link.targetNodeId); if (!source || !target) return null; const path = pathFor(source, target), selected = editor.selection.connectionId === link.id; return <g key={link.id}><path d={path} fill="none" stroke={selected ? "white" : link.outcome === "success" ? "#34d399" : link.outcome === "failure" ? "#f87171" : "#c084fc"} strokeWidth={selected ? 4 : 2} markerEnd="url(#dialogue-arrow)" /><path d={path} fill="none" stroke="transparent" strokeWidth="16" className="pointer-events-stroke cursor-pointer" onClick={(event) => { event.stopPropagation(); dispatch(dialogueEditorConnectionSelected(link.id)); }} /></g>; })}</svg>
    {editor.document.nodes.map((node) => { const selected = editor.selection.nodeId === node.id; const Icon = node.kind === "npc-text" ? MessageSquareText : node.kind === "choice" ? MessagesSquare : node.kind === "skill-chain" ? ShieldQuestion : Flag; const title = node.kind === "npc-text" ? "NPC text" : node.kind === "choice" ? "Player choice" : node.kind === "skill-chain" ? node.label : node.title; const preview = node.kind === "npc-text" || node.kind === "choice" ? node.text : node.kind === "skill-chain" ? `${node.tasks.length} ordered task${node.tasks.length === 1 ? "" : "s"} · conversation total 6 AP` : `${node.endingKind} · ${node.transformation}`; const outcomes = node.kind === "skill-chain" ? (["success", "failure"] as const) : node.kind === "ending" ? [] : (["next"] as const); return <div key={node.id} className={`absolute select-none border bg-slate-950/95 shadow-xl ${selected ? "border-white ring-2 ring-white/40" : node.kind === "ending" ? "border-amber-400" : "border-violet-500"}`} style={{ left: node.position.x, top: node.position.y, width: cardWidth, minHeight: cardHeight }} onClick={(event) => { event.stopPropagation(); editor.pendingConnection ? dispatch(dialogueEditorConnectionTargetSelected(node.id)) : dispatch(dialogueEditorNodeSelected(node.id)); }}>
      <div className="flex cursor-grab items-center gap-2 border-b border-slate-700 bg-slate-900 px-3 py-2" onPointerDown={(event) => { if (editor.pendingConnection) return; const p = point(event); event.currentTarget.setPointerCapture(event.pointerId); dispatch(dialogueEditorNodeDragStarted({ nodeId: node.id, offset: { x: p.x - node.position.x, y: p.y - node.position.y } })); }}><Icon size={13} className="text-violet-200" /><div className="min-w-0 flex-1 truncate text-[10px] font-bold uppercase">{title}</div>{editor.document.startNodeId === node.id && <span className="text-[8px] text-emerald-300">START</span>}</div>
      <div className="line-clamp-2 min-h-10 p-2 text-[9px] text-slate-400">{preview || "No text"}</div><div className="flex justify-end gap-1 px-2 pb-2">{outcomes.map((outcome) => <button key={outcome} type="button" title={`Connect ${outcome}`} onClick={(event) => { event.stopPropagation(); dispatch(dialogueEditorConnectionStarted({ sourceNodeId: node.id, outcome })); }} className={`flex items-center gap-1 border px-2 py-1 text-[8px] uppercase ${outcome === "success" ? "border-emerald-600 text-emerald-200" : outcome === "failure" ? "border-red-700 text-red-200" : "border-violet-600 text-violet-200"}`}><Link2 size={9} />{outcome}</button>)}</div>
    </div>; })}
    {editor.pendingConnection && <div className="absolute left-4 top-4 border border-amber-400 bg-amber-950/90 px-3 py-2 text-[10px] text-amber-100">Select a destination node for {editor.pendingConnection.outcome}</div>}
  </div>;
};
export default DialogueGraph;
