export type CombatSide = "player" | "enemy";
export interface GridPoint { x: number; y: number }
export interface WallSegment { id: string; from: GridPoint; to: GridPoint }
export interface DoorSegment extends WallSegment { open: boolean; locked?: boolean }
export interface MapObject { id: string; kind: "console" | "cover" | "prisoner" | "extraction" | "control"; position: GridPoint; label: string; completed?: boolean; coverType?: "low-cover" | "console" | "close-machinery" }
export interface FireSpreadEvent { turn: number; source: GridPoint; fire: GridPoint; smoke: GridPoint }
export type WoundState = "healthy" | "light" | "serious" | "unconscious" | "dead";
export type MoraleState = "steady" | "shaken" | "panicked" | "surrendered";
export type LightingLevel = "illuminated" | "emergency" | "dark";
export type TerrainType = "difficult" | "elevated" | "hazardous";
export type WeaponRangeBand = "effective" | "long" | "extreme";
export type WeaponVisualCategory = "pistol" | "shotgun" | "smg" | "rifle" | "laser-rifle" | "gauss-rifle";
export type WeaponAmmunitionKind = "discard-sabot" | "he" | "heap" | "flechette";
export interface WeaponAmmunitionProfile { kind: WeaponAmmunitionKind; label: string; effectiveRange: number; longRange: number; extremeRange: number; penetration: number; automatic?: boolean; automaticFireBonusByRange?: Partial<Record<WeaponRangeBand, number>>; accuracyByRange?: Partial<Record<WeaponRangeBand, number>>; penetrationByRange?: Partial<Record<WeaponRangeBand, number>>; woundEscalation?: boolean; collateralBlast?: boolean }
export interface WeaponProfile { name: string; effectiveRange: number; longRange: number; extremeRange: number; penetration: number; automatic: boolean; automaticFireBonusByRange?: Partial<Record<WeaponRangeBand, number>>; inherentAutomaticFireBonus?: boolean; highEnergy?: boolean; enhancedVision?: boolean; collateralBlast?: boolean; woundEscalation?: boolean; ammunitionKind?: WeaponAmmunitionKind; ammunitionProfiles?: WeaponAmmunitionProfile[]; magazineSize?: number; visualCategory?: WeaponVisualCategory; accuracy?: number; accuracyByRange?: Partial<Record<WeaponRangeBand, number>>; penetrationByRange?: Partial<Record<WeaponRangeBand, number>> }
export interface Combatant { id: string; name: string; side: CombatSide; sourceCrewId?: string; sourceCharacterId?: string | null; reinforcementTurn?: number; position: GridPoint; facing: "north" | "east" | "south" | "west"; posture?: "standing" | "prone"; visionMode?: "normal" | "enhanced"; hasLamp?: boolean; lampOn?: boolean; concealed?: boolean; health: number; defeated: boolean; surrendered: boolean; weapon: WeaponProfile; weaponSkill: number; meleeWeapon: { name: string; penetration: number }; meleeRating: number; leadershipRating?: number; armor: number; armorName?: string; grenades: number; smokeGrenades?: number; stunGrenades?: number; flareGrenades?: number; stunnedUntilTurn?: number; medkits: number; breachingCharges?: number; vaccSuit?: boolean; woundState: WoundState; seriousWounds?: number }
export interface CombatScenario {
  id: string; title: string; briefing: string; objective: string; width: number; height: number;
  walls: WallSegment[]; doors: DoorSegment[]; objects: MapObject[]; combatants: Combatant[]; gravityMode?: "normal" | "zero-g"; defaultLighting?: LightingLevel; lightingByCell?: Record<string, LightingLevel>; terrainByCell?: Record<string, TerrainType>; elevationAccessCells?: GridPoint[]; flareCells?: GridPoint[]; handholds?: GridPoint[]; vacuumSources?: GridPoint[]; fireCells?: GridPoint[]; smokeCells?: GridPoint[]; criticalFireCells?: GridPoint[]; fireSpreadSchedule?: FireSpreadEvent[]; criticalFireDeadlineTurn?: number; victoryCondition?: "secure-objective" | "rescue-extract" | "hold-zone" | "staged-objectives" | "capture-target"; captiveId?: string; captureTargetId?: string; holdUntilTurn?: number; stageObjectiveIds?: string[]; stageUnlockDoorId?: string; defendedObjectiveByCombatantId?: Record<string, string>; flankBiasByCombatantId?: Record<string, "left" | "right">; contestedObjectiveIds?: string[];
}
export type CharacterCombatHudId = "action" | "scenario" | "character" | "crewRoster" | "enemyRoster" | "events" | "legend" | "outcome";
export type CharacterCombatViewMode = "2d" | "3d";
export type ArmoryLoadoutId = "scout" | "breacher" | "assault" | "heavy" | "plasma" | "fusion" | "action-ram" | "lag";
export interface CharacterCombatCamera { quarterTurn: 0 | 1 | 2 | 3; azimuth: number; elevation: number; zoom: number; focus: GridPoint | null; pan: GridPoint }
export interface CombatantStart { id: string; name: string; sourceCrewId?: string; sourceCharacterId?: string | null; woundState: WoundState; grenades: number; medkits: number }
export interface CombatOutcomeMember { id: string; name: string; sourceCrewId?: string; sourceCharacterId?: string | null; condition: "survived" | "wounded" | "incapacitated" | "dead"; woundState: WoundState; grenadesUsed: number; medkitsUsed: number }
export interface CombatOutcome { result: "victory" | "defeat"; scenarioTitle: string; turn: number; members: CombatOutcomeMember[]; enemiesNeutralized: number; enemiesSurrendered: number; campaignChangesApplied: false }
export type FireMode = "snap" | "aimed" | "automatic" | "suppressive" | "covering" | "melee";
export interface CharacterCombatHudLayout { visible: boolean; pinned: boolean; position: GridPoint }
export interface CoveringFireLane { attackerId: string; target: GridPoint; cells: GridPoint[] }
export interface OverwatchLane { attackerId: string; target: GridPoint; cells: GridPoint[] }
export interface SoundContact { id: string; sourceEnemyId: string; point: GridPoint; kind: "movement" | "door" | "weapon" | "equipment"; expiresAtTurn: number }
export interface PlayerNoiseContact { sourcePlayerId: string; point: GridPoint; expiresAtTurn: number }
export interface GrenadeImpact { kind: "fragmentation" | "smoke" | "stun" | "flare"; intended: GridPoint; landing: GridPoint; scattered: boolean; blastCells: GridPoint[] }
export interface WeaponImpact { weaponName: string; ammunitionKind?: WeaponAmmunitionKind; ammunitionLabel: string; point: GridPoint; blastCells: GridPoint[]; hit: boolean }
export interface CombatantMovementAnimation { sequence: number; path: GridPoint[]; mode: "walk" | "run" }
export interface CharacterCombatState { scenario: CombatScenario | null; selectedBoardingTeamIds: string[]; armoryLoadoutIds: [ArmoryLoadoutId, ArmoryLoadoutId]; combatantStarts: Record<string, CombatantStart>; outcome: CombatOutcome | null; viewMode: CharacterCombatViewMode; camera: CharacterCombatCamera; status: "active" | "victory" | "defeat"; turn: number; selectedCombatantId: string | null; plannedMove: PlannedMove | null; plannedAttackTargetId: string | null; plannedAttackMode: FireMode | null; grenadeTargeting: boolean; plannedGrenadeTarget: GridPoint | null; lastGrenadeImpact: GrenadeImpact | null; plannedOpenDoorId: string | null; plannedBreachDoorId: string | null; plannedExtinguishFire: GridPoint | null; smokeClearsAtTurnByCell: Record<string, number>; placedBreachingChargeByDoorId: Record<string, string>; vacuumExposureByCombatantId: Record<string, number>; coveringFireTargeting: boolean; plannedCoveringFireTarget: GridPoint | null; coveringFireLanes: CoveringFireLane[]; overwatchTargeting: boolean; plannedOverwatchTarget: GridPoint | null; overwatchLanes: OverwatchLane[]; plannedTreatmentTargetId: string | null; recoveringCombatantIds: string[]; evadingCombatantIds: string[]; trottingCombatantIds: string[]; bracedCombatantIds: string[]; suppressedCombatantIds: string[]; draggingCombatantByCarrierId: Record<string, string>; maintainedTargetByCombatantId: Record<string, string>; plannedObjectiveId: string | null; hoveredDestination: GridPoint | null; actionPointsById: Record<string, number>; ammunitionById: Record<string, number>; actedCombatantIds: string[]; events: string[]; hudLayouts: Record<CharacterCombatHudId, CharacterCombatHudLayout> }
export interface CharacterCombatState { leaderIdBySide?: Record<CombatSide, string | null>; moraleStateByCombatantId?: Record<string, MoraleState>; grenadeKind?: "fragmentation" | "smoke" | "stun" | "flare" | null; flareClearsAtTurnByCell?: Record<string, number>; observedEnemyIds?: string[]; lastKnownEnemyPositions?: Record<string, GridPoint>; observersByEnemyId?: Record<string, string[]>; soundContacts?: SoundContact[]; playerNoiseContacts?: PlayerNoiseContact[]; cautiousMovementCombatantIds?: string[]; investigationTargetByEnemyId?: Record<string, GridPoint>; coveredDoorByCombatantId?: Record<string, string>; doorCoverTargeting?: boolean; plannedCoveredDoorId?: string | null; weaponReadyCombatantIds?: string[]; advanceReadyCombatantIds?: string[]; aimedTargetByCombatantId?: Record<string, string>; calledShotByCombatantId?: Record<string, "weapon" | "mobility" | "body">; weaponDamagedCombatantIds?: string[]; mobilityImpairedCombatantIds?: string[]; plannedMeleeMode?: "ahl" | "subdue" | null; processedEnemyPhaseCombatantIds?: string[]; disengagedCombatantIds?: string[]; reactionMeleeUsedCombatantIds?: string[] }
export interface PlannedMove { combatantId: string; destination: GridPoint; path: GridPoint[]; cost: number; kind?: "move" | "drop" | "climb" | "dive" | "melee-dive" | "enemy-entry" | "crawl"; finalFacing?: Combatant["facing"]; costBreakdown?: string[]; meleeTargetId?: string }
export interface CharacterCombatState { diveTargeting?: boolean }
export interface CharacterCombatState { extendedArmoryLoadoutIds?: ArmoryLoadoutId[] }
export interface CharacterCombatState { adjacencyReactionReserveById?: Record<string, number>; adjacencyReactionUsedCombatantIds?: string[]; movedCombatantIds?: string[]; pendingAdjacencyReaction?: { reactorId: string; moverId: string; trigger: GridPoint } | null }
export interface CharacterCombatState { structuralDamageById?: Record<string, number> }
export interface CharacterCombatState { ammunitionByCombatantAndKind?: Record<string, Partial<Record<WeaponAmmunitionKind, number>>> }
export interface CharacterCombatState { lastWeaponImpact?: WeaponImpact | null }
export interface CharacterCombatState { ahlMeleeStunUntilTurnById?: Record<string, number> }
export interface CharacterCombatState { ahlMeleeEngagedCombatantIds?: string[] }
export interface CharacterCombatState { ahlMeleeDeclarations?: { attackerId: string; targetId: string; roll: number; responseRoll: number; tieBreaker: number; sameSquare: boolean; attackerDived: boolean }[] }
export interface CharacterCombatState { awaitingAhlMeleeAcknowledgement?: boolean; lastResolvedAhlMeleeDeclarations?: { attackerId: string; targetId: string; roll: number; responseRoll: number; tieBreaker: number; sameSquare: boolean; attackerDived: boolean }[]; lastAhlMeleeResults?: string[] }
export interface CharacterCombatState { structuralTargeting?: boolean; plannedStructuralTargetId?: string | null }
export interface CharacterCombatState { enemySquareEnteredCombatantIds?: string[] }
export interface CharacterCombatState { movementAnimationByCombatantId?: Record<string, CombatantMovementAnimation> }
