import type { StarSystemViewModel } from "@/lib/starSystemViewModel";
import { buildSystemSceneGraph } from "../sceneGraph";

const starColors = {
  core: "#fff5a0",
  mid: "#fff2d0",
  limb: "#f0dca8",
  glow: "#fff0b4",
};

const model: StarSystemViewModel = {
  source: {
    sectorAbbr: "Spin",
    hex: "1910",
    worldName: "Regina",
    systemId: "Spin:1910",
    dataSource: "canonical",
  },
  sourceSystem: null,
  stars: [
    {
      id: "star:0",
      label: "Primary",
      dataSource: "canonical",
      focusState: "none",
      kind: "star",
      source: {
        index: 0,
        role: "primary",
        spectral: "F7 V",
        dataSource: "canonical",
        stellarClass: "main-sequence",
        color: "#fff2d0",
        radiusScale: 1,
        habitableZone: null,
        orbitId: null,
        au: null,
        proximity: null,
      },
      index: 0,
      role: "primary",
      spectral: "F7 V",
      stellarClass: "main-sequence",
      color: "#fff2d0",
      colors: starColors,
      massSolar: 1,
      physicalRadiusScale: 1,
      sceneRadius: 0.3,
      orbit: {
        orbitId: null,
        au: null,
        sceneRadius: 4,
        angle0: 0,
        angularVelocity: 0,
        center: { x: 0, y: 0, z: 0 },
      },
      habitableZone: null,
    },
  ],
  orbits: [
    {
      id: "orbit:1",
      label: "Orbit 1",
      dataSource: "canonical",
      focusState: "none",
      kind: "orbit",
      orbitKind: "primary",
      orbitId: 1,
      au: 1,
      zone: "habitable",
      sceneRadius: 10,
      angle0: 0,
      parentId: "star:0",
      bodyId: "body:1",
      source: null,
    },
    {
      id: "orbit:1:moon:0",
      label: "Moon Orbit",
      dataSource: "canonical",
      focusState: "none",
      kind: "orbit",
      orbitKind: "satellite",
      orbitId: 1,
      au: null,
      zone: null,
      sceneRadius: 2,
      angle0: Math.PI / 2,
      parentId: "body:1",
      bodyId: "body:1:moon:0",
      source: null,
    },
  ],
  bodies: [
    {
      id: "body:1",
      label: "Regina",
      dataSource: "canonical",
      focusState: "current",
      kind: "world",
      source: {
        kind: "world",
        isMainWorld: true,
        dataSource: "canonical",
        name: "Regina",
        sizeCode: "8",
        diameterKm: 12800,
        atmosphereCode: "6",
        atmosphereType: "standard",
        hydrographicsCode: "6",
        surfaceType: "terran",
        tradeCodes: [],
        axialTilt: null,
        rotationPeriodH: null,
        canonicalTexture: null,
        moons: [],
        hasRings: null,
      },
      sourceOrbit: null,
      orbitId: 1,
      parentId: "star:0",
      isMainWorld: true,
      tradeCodes: [],
      scene: {
        orbitRadius: 10,
        angle0: 0,
        position: null,
      },
      visuals: {
        sceneRadius: 0.2,
        color: null,
        textureKey: "terran",
        hasAtmosphere: true,
        hasRings: false,
        labelVisible: true,
      },
      sizeCode: "8",
      diameterKm: 12800,
      atmosphereCode: "6",
      hydrographicsCode: "6",
      surfaceType: "terran",
    },
    {
      id: "body:1:moon:0",
      label: "Satellite",
      dataSource: "canonical",
      focusState: "none",
      kind: "world",
      source: {
        kind: "world",
        isMainWorld: false,
        dataSource: "canonical",
        name: "Satellite",
        sizeCode: "2",
        diameterKm: 3200,
        atmosphereCode: "0",
        atmosphereType: "none",
        hydrographicsCode: "0",
        surfaceType: "barren",
        tradeCodes: [],
        axialTilt: null,
        rotationPeriodH: null,
        canonicalTexture: null,
        moons: [],
        hasRings: null,
      },
      sourceOrbit: null,
      orbitId: 1,
      parentId: "body:1",
      isMainWorld: false,
      tradeCodes: [],
      scene: {
        orbitRadius: 2,
        angle0: Math.PI / 2,
        position: null,
      },
      visuals: {
        sceneRadius: 0.12,
        color: null,
        textureKey: "barren",
        hasAtmosphere: false,
        hasRings: false,
        labelVisible: true,
      },
      sizeCode: "2",
      diameterKm: 3200,
      atmosphereCode: "0",
      hydrographicsCode: "0",
      surfaceType: "barren",
    },
  ],
  unplacedBodies: [],
  scene: {
    center: { x: 0, y: 0, z: 0 },
    cameraDistance: 15,
    outermostOrbitRadius: 10,
  },
  counts: {
    stars: 1,
    orbits: 2,
    bodies: 2,
    worlds: 2,
    gasGiants: 0,
    belts: 0,
  },
};

describe("buildSystemSceneGraph", () => {
  it("positions stars, orbit centers, and bodies from parent anchors", () => {
    const graph = buildSystemSceneGraph(model);

    expect(graph.stars[0]).toMatchObject({
      x: 4,
      y: 0,
      z: 0,
    });
    expect(graph.orbits[0]).toMatchObject({
      x: 4,
      y: 0,
      z: 0,
    });
    expect(graph.bodies[0]).toMatchObject({
      x: 14,
      y: 0,
      z: 0,
    });
    expect(graph.orbits[1]).toMatchObject({
      x: 14,
      y: 0,
      z: 0,
    });
    expect(graph.bodies[1].x).toBeCloseTo(14);
    expect(graph.bodies[1].z).toBeCloseTo(2);
  });
});
